//image light box
$(document).ready(function() 
{
  $('.img_container').magnificPopup
  ({
 	delegate: 'a', // child items selector, by clicking on it popup will open
  	type: 'image',
  	gallery:
  	{
    	enabled:true
  	}
 });
});
//logo
$(document).ready(function() 
{
	$('#logo').owlCarousel({
	    loop:true,
	    smartSpeed:4000,
	    margin:10,
	    nav:true,
	    responsive:{
	        0:{
	            items:1
	        },
	        600:{
	            items:3
	        },
	        1000:{
	            items:5
	        }
	    }
	})
});
//work carousel
$(document).ready(function() 
{
	$('#owl_work').owlCarousel({
	    loop:true,
	    smartSpeed:4000,
	    margin:10,
	    nav:true,
	    responsive:{
	        0:{
	            items:1
	        },
	        600:{
	            items:3
	        },
	        1000:{
	            items:3
	        }
	    }
	})
});
//quotes
$(document).ready(function() 
{
	$('#customers').owlCarousel({
	    loop:true,
	    smartSpeed:4000,
	    margin:10,
	    nav:true,
	    responsive:{
	        0:{
	            items:1
	        },
	        600:{
	            items:3
	        },
	        1000:{
	            items:2
	        }
	    }
	})
});
//navbar transition
$(document).ready(function() 
{
	$(window).scroll(function()
	{
		var location=$(this).scrollTop();
		if(location<70)
		{
			$("nav").removeClass("transparent");
		}
		else
		{
			$("nav").addClass("transparent");
		}
	});
});